from __future__ import annotations

from collections.abc import Callable

from app.providers.llm.base import (
    LLMMessage,
    LLMProvider,
    LLMResponse,
)


class MockLLMProvider(LLMProvider):
    """
    Deterministic LLM provider for local development and tests.

    Responses are supplied by the caller instead of generated by an
    external model.
    """

    def __init__(
        self,
        *,
        responses: list[LLMResponse] | None = None,
        responder: Callable[
            [list[LLMMessage], str | None, list[dict] | None],
            LLMResponse,
        ]
        | None = None,
    ) -> None:
        if responses is None and responder is None:
            raise ValueError("Either responses or responder must be provided.")

        if responses is not None and responder is not None:
            raise ValueError("Provide either responses or responder, not both.")

        self._responses = list(responses or [])
        self._responder = responder
        self.calls: list[dict] = []

    async def generate(
        self,
        *,
        messages: list[LLMMessage],
        system_prompt: str | None = None,
        tools: list[dict] | None = None,
    ) -> LLMResponse:
        self.calls.append(
            {
                "messages": messages,
                "system_prompt": system_prompt,
                "tools": tools,
            }
        )

        if self._responder is not None:
            return self._responder(
                messages,
                system_prompt,
                tools,
            )

        if not self._responses:
            raise RuntimeError("MockLLMProvider has no responses remaining.")

        return self._responses.pop(0)
